# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Yuesong's Homepage"
masthead_title: " "
name: Yuesong Shen
logo: assets/favicon/favicon.ico
twitter_username: ysngshn
github_username: ysngshn
minimal_mistakes_skin: "default"
minimal_mistakes_skin_dark: "dark"
search: true

# Build settings
markdown: kramdown
remote_theme: ysngshn/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - local_resources/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Yuesong Shen"
  avatar : "/assets/images/profile-photo.jpg"
  bio    : >- 
    <a href="https://upload.wikimedia.org/wikipedia/commons/8/87/Chinese_woodcut%3B_Daoist_internal_alchemy_%289%29_Wellcome_L0038979.jpg">
    <del title="This is a joke, or is it?">
    Deep learning alchemist<br>
    Bayesian sect<br>
    </del>
    </a>
    PhD student @ <a href="https://cvg.cit.tum.de">TUM CVG</a><br>
    (firstname).(lastname)@tum.de
  links:
    - label: "CVG Page"
      icon: "fa-solid fa-fw fa-flask"
      url: "https://cvg.cit.tum.de/members/sheny"
    - label: "LinkedIn"
      icon: "fa-brands fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shen-yuesong-a46b0981"
    - label: "Google Scholar"
      icon: "fa-brands fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=apVTXosAAAAJ&hl=en"
    - label: "X (Twitter)"
      icon: "fa-brands fa-fw fa-x-twitter"
      url: "https://twitter.com/ysngshn"
    - label: "GitHub"
      icon: "fa-brands fa-fw fa-github"
      url: "https://github.com/ysngshn"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
